USE sourcecode;

INSERT INTO product_records (
  id,
  title,
  slug,
  price,
  category_id,
  tech_stack,
  repository,
  description,
  cover_image_path,
  detail_image_paths,
  zip_file_name,
  zip_file_path,
  created_by
) VALUES
  ("prd-0001", "Ecommerce React Starter", "ecommerce-react-starter", 29.0, "commerce", "React, TypeScript, Stripe", NULL, "Landing ecommerce với thanh toán Stripe, giao diện rõ ràng và dễ tuỳ biến.", "asset:source1.jpg", "asset-detail:detail1.jpg", "Lab1-Ajax_demo.zip", "Frontend/src/assets/file zip/Lab1-Ajax_demo.zip", NULL),
  ("prd-0002", "Shop Admin Dashboard", "shop-admin-dashboard", 39.0, "management", "React, Chart.js, REST API", NULL, "Dashboard quản trị đơn hàng và khách hàng, biểu đồ trực quan.", "asset:source3.jpg", "asset-detail:detail2.jpg", "Lab1-Ajax_demo.zip", "Frontend/src/assets/file zip/Lab1-Ajax_demo.zip", NULL),
  ("prd-0003", "Food Order SPA", "food-order-spa", 25.0, "food", "React, Redux, Map", NULL, "Giao diện đặt món nhanh, có theo dõi trạng thái đơn hàng.", "asset:source5.jpg", "asset-detail:detail3.jpg", "Lab1-Ajax_demo.zip", "Frontend/src/assets/file zip/Lab1-Ajax_demo.zip", NULL),
  ("prd-0004", "SaaS Landing Portal", "saas-landing-portal", 19.0, "portal", "React, Tailwind, SEO", NULL, "Landing cho sản phẩm SaaS, tối ưu SEO và chuyển đổi.", "asset:source2.jpg", "asset-detail:detail4.jpg", "Lab1-Ajax_demo.zip", "Frontend/src/assets/file zip/Lab1-Ajax_demo.zip", NULL),
  ("prd-0005", "Utility Invoice Maker", "utility-invoice-maker", 18.0, "utility", "React, PDF, LocalStorage", NULL, "Tạo hoá đơn và xuất PDF chỉ với vài bước.", "asset:source4.jpg", "asset-detail:detail5.jpg", "Lab1-Ajax_demo.zip", "Frontend/src/assets/file zip/Lab1-Ajax_demo.zip", NULL),
  ("prd-0006", "AI Resume Generator", "ai-resume-generator", 45.0, "ai", "React, OpenAI, Prompt", NULL, "Tạo CV bằng AI với mẫu sẵn, chỉnh sửa nhanh.", "asset:source6.jpg", "asset-detail:detail6.jpg", "Lab1-Ajax_demo.zip", "Frontend/src/assets/file zip/Lab1-Ajax_demo.zip", NULL),
  ("prd-0007", "Ecommerce Product Grid", "ecommerce-product-grid", 22.0, "commerce", "React, Filters, Pagination", NULL, "Lưới sản phẩm có bộ lọc và phân trang mượt.", "asset:source7.jpg", "asset-detail:detail7.jpg", "Lab1-Ajax_demo.zip", "Frontend/src/assets/file zip/Lab1-Ajax_demo.zip", NULL),
  ("prd-0008", "Travel Booking Portal", "travel-booking-portal", 34.0, "portal", "React, Calendar, Map", NULL, "Portal đặt tour với lịch trình và bản đồ.", "asset:source8.jpg", "asset-detail:detail8.jpg", "Lab1-Ajax_demo.zip", "Frontend/src/assets/file zip/Lab1-Ajax_demo.zip", NULL),
  ("prd-0009", "Restaurant POS", "restaurant-pos", 49.0, "food", "React, POS, Offline", NULL, "POS nhà hàng hỗ trợ offline và đồng bộ khi có mạng.", "asset:souce9.jpg", "asset-detail:detail9.jpg", "Lab1-Ajax_demo.zip", "Frontend/src/assets/file zip/Lab1-Ajax_demo.zip", NULL),
  ("prd-0010", "Warehouse Manager", "warehouse-manager", 55.0, "management", "React, Inventory, Barcode", NULL, "Quản lý kho và nhập xuất, hỗ trợ mã vạch.", "asset:source10.jpg", "asset-detail:detail10.jpg", "Lab1-Ajax_demo.zip", "Frontend/src/assets/file zip/Lab1-Ajax_demo.zip", NULL),
  ("prd-0011", "Invoice Tracker", "invoice-tracker", 17.0, "utility", "React, Table, Export CSV", NULL, "Theo dõi công nợ và xuất CSV tiện lợi.", "asset:source1.jpg", "asset-detail:detail11.jpg", "Lab1-Ajax_demo.zip", "Frontend/src/assets/file zip/Lab1-Ajax_demo.zip", NULL),
  ("prd-0012", "AI Chat Landing", "ai-chat-landing", 23.0, "ai", "React, UI Kit, Landing", NULL, "Landing giới thiệu chatbot AI chuyên nghiệp.", "asset:source2.jpg", "asset-detail:detail12.jpg", "Lab1-Ajax_demo.zip", "Frontend/src/assets/file zip/Lab1-Ajax_demo.zip", NULL),
  ("prd-0013", "Digital Marketplace", "digital-marketplace", 59.0, "commerce", "React, Payment, Reviews", NULL, "Chợ mua bán sản phẩm số, có đánh giá.", "asset:source3.jpg", "asset-detail:detail13.jpg", "Lab1-Ajax_demo.zip", "Frontend/src/assets/file zip/Lab1-Ajax_demo.zip", NULL),
  ("prd-0014", "Student Portal", "student-portal", 28.0, "portal", "React, Auth, Profile", NULL, "Portal sinh viên và thông tin học tập.", "asset:source4.jpg", "asset-detail:detail14.jpg", "Lab1-Ajax_demo.zip", "Frontend/src/assets/file zip/Lab1-Ajax_demo.zip", NULL),
  ("prd-0015", "Coffee Shop App", "coffee-shop-app", 26.0, "food", "React, Menu, Order", NULL, "Menu cà phê và đặt món nhanh chóng.", "asset:source5.jpg", "asset-detail:detail15.jpg", "Lab1-Ajax_demo.zip", "Frontend/src/assets/file zip/Lab1-Ajax_demo.zip", NULL),
  ("prd-0016", "Project Tracker", "project-tracker", 42.0, "management", "React, Kanban, Teams", NULL, "Quản lý dự án dạng Kanban, hỗ trợ nhóm.", "asset:source6.jpg", "asset-detail:detail16.jpg", "Lab1-Ajax_demo.zip", "Frontend/src/assets/file zip/Lab1-Ajax_demo.zip", NULL),
  ("prd-0017", "Expense Planner", "expense-planner", 15.0, "utility", "React, Budget, Charts", NULL, "Kế hoạch chi tiêu cá nhân với biểu đồ.", "asset:source7.jpg", "asset-detail:detail17.jpg", "Lab1-Ajax_demo.zip", "Frontend/src/assets/file zip/Lab1-Ajax_demo.zip", NULL),
  ("prd-0018", "AI Content Studio", "ai-content-studio", 49.0, "ai", "React, OpenAI, Editor", NULL, "Tạo nội dung marketing bằng AI, chỉnh sửa nhanh.", "asset:source8.jpg", "asset-detail:detail18.jpg", "Lab1-Ajax_demo.zip", "Frontend/src/assets/file zip/Lab1-Ajax_demo.zip", NULL),
  ("prd-0019", "Fashion Store", "fashion-store", 31.0, "commerce", "React, Catalog, Wishlist", NULL, "Cửa hàng thời trang có wishlist.", "asset:souce9.jpg", "asset-detail:detail19.jpg", "Lab1-Ajax_demo.zip", "Frontend/src/assets/file zip/Lab1-Ajax_demo.zip", NULL),
  ("prd-0020", "Service Booking Portal", "service-booking-portal", 36.0, "portal", "React, Booking, Email", NULL, "Portal đặt lịch dịch vụ và gửi email xác nhận.", "asset:source10.jpg", "asset-detail:detail20.jpg", "Lab1-Ajax_demo.zip", "Frontend/src/assets/file zip/Lab1-Ajax_demo.zip", NULL),
  ("prd-0021", "Food Delivery Dashboard", "food-delivery-dashboard", 38.0, "food", "React, Fleet, Status", NULL, "Theo dõi đơn giao hàng theo trạng thái.", "asset:source1.jpg", "asset-detail:detail21.jpg", "Lab1-Ajax_demo.zip", "Frontend/src/assets/file zip/Lab1-Ajax_demo.zip", NULL),
  ("prd-0022", "CRM Lite", "crm-lite", 44.0, "management", "React, CRM, Pipelines", NULL, "CRM nhỏ gọn cho sales, quản lý pipeline.", "asset:source2.jpg", "asset-detail:detail22.jpg", "Lab1-Ajax_demo.zip", "Frontend/src/assets/file zip/Lab1-Ajax_demo.zip", NULL),
  ("prd-0023", "Notes Organizer", "notes-organizer", 12.0, "utility", "React, Tags, Search", NULL, "Ghi chú với tag và tìm kiếm nhanh.", "asset:source3.jpg", "asset-detail:detail23.jpg", "Lab1-Ajax_demo.zip", "Frontend/src/assets/file zip/Lab1-Ajax_demo.zip", NULL),
  ("prd-0024", "AI Product Copy", "ai-product-copy", 33.0, "ai", "React, OpenAI, Form", NULL, "Sinh mô tả sản phẩm bằng AI, tuỳ chỉnh nhanh.", "asset:source4.jpg", "asset-detail:detail24.jpg", "Lab1-Ajax_demo.zip", "Frontend/src/assets/file zip/Lab1-Ajax_demo.zip", NULL),
  ("prd-0025", "Grocery Store", "grocery-store", 27.0, "commerce", "React, Cart, Coupons", NULL, "Siêu thị mini với cart và coupon.", "asset:source5.jpg", "asset-detail:detail25.jpg", "Lab1-Ajax_demo.zip", "Frontend/src/assets/file zip/Lab1-Ajax_demo.zip", NULL),
  ("prd-0026", "Company Intranet", "company-intranet", 32.0, "portal", "React, News, Docs", NULL, "Intranet nội bộ cho công ty, chia sẻ tin tức.", "asset:source6.jpg", "asset-detail:detail26.jpg", "Lab1-Ajax_demo.zip", "Frontend/src/assets/file zip/Lab1-Ajax_demo.zip", NULL),
  ("prd-0027", "Restaurant Table Booking", "restaurant-table-booking", 24.0, "food", "React, Reservation, SMS", NULL, "Đặt bàn nhà hàng nhanh và tiện lợi.", "asset:source7.jpg", "asset-detail:detail27.jpg", "Lab1-Ajax_demo.zip", "Frontend/src/assets/file zip/Lab1-Ajax_demo.zip", NULL),
  ("prd-0028", "Asset Manager", "asset-manager", 46.0, "management", "React, Assets, Audit", NULL, "Quản lý tài sản và kiểm kê định kỳ.", "asset:source8.jpg", "asset-detail:detail28.jpg", "Lab1-Ajax_demo.zip", "Frontend/src/assets/file zip/Lab1-Ajax_demo.zip", NULL),
  ("prd-0029", "Task Timer", "task-timer", 14.0, "utility", "React, Timer, Reports", NULL, "Theo dõi thời gian làm việc và báo cáo.", "asset:souce9.jpg", "asset-detail:detail29.jpg", "Lab1-Ajax_demo.zip", "Frontend/src/assets/file zip/Lab1-Ajax_demo.zip", NULL),
  ("prd-0030", "AI Image Prompt Lab", "ai-image-prompt-lab", 41.0, "ai", "React, Prompt, Gallery", NULL, "Thử nghiệm prompt cho ảnh AI và bộ sưu tập.", "asset:source10.jpg", "asset-detail:detail30.jpg", "Lab1-Ajax_demo.zip", "Frontend/src/assets/file zip/Lab1-Ajax_demo.zip", NULL);
